version = 1

exclude_patterns = ["src/api/fship_app/migrations/**"]

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]